{% set name = "randonneur_data" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/randonneur_data-{{ version }}.tar.gz
  sha256: 0fdc9c318b9b6c2a065887c985fe2418144d430180887e3222b6115d5b2b69e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0
    - pip
  run:
    - python >=3.9

test:
  imports:
    - randonneur_data
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Data for the randonneur ETL library and spec
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
